[platformio]
default_envs = t_embed_cc1101_plus
boards_dir = boards

[env:t_embed_cc1101_plus]
platform = espressif32@6.13.0
board = t_embed_cc1101_plus
framework = arduino
board_build.partitions = partitions.csv

upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

extra_scripts = post:scripts/merge_bin.py

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -O2
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DFASTLED_RMT_BUILTIN_DRIVER=1
    -DFASTLED_RMT_MAX_CHANNELS=1
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=170
    -DTFT_HEIGHT=320
    -DTFT_MISO=10
    -DTFT_MOSI=9
    -DTFT_SCLK=11
    -DTFT_CS=41
    -DTFT_DC=16
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DTFT_INVERSION_ON=1
    -DTFT_SPI_MODE=SPI_MODE0
    -DUSE_HSPI_PORT=1
    -DSUPPORT_TRANSACTIONS=1
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=16000000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DDISABLE_ALL_LIBRARY_WARNINGS=1
    -DRADIOLIB_STATIC_ONLY=1
    -Wall
    -Wextra
    -Wshadow
    -Wformat=2

lib_deps =
    https://github.com/FastLED/FastLED.git#3.10.3
    bodmer/TFT_eSPI@2.5.43
    jgromes/RadioLib@7.7.1
    adafruit/Adafruit PN532@1.3.4
    crankyoldgit/IRremoteESP8266@2.8.6
